FROM ubuntu:lunar

RUN mkdir -p /sdwa

ADD . /sdwa/

RUN apt-get update && apt-get upgrade -y && apt-get install -y python3-pip

WORKDIR /sdwa

RUN cd /sdwa && pip3 install -r requirements.txt --break-system-packages

RUN cd /sdwa && rm -f db/vuln_db.sqlite && python3 db/setup_db.py

ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

CMD ["flask", "run", "-h", "0.0.0.0"]
